/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/scene.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Office(props) {
  const { nodes, materials } = useGLTF("/models/scene.glb");
  const group = useRef();

  const texture = useTexture("/textures/baked.jpg");
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Plane">
          <mesh
            name="Plane_1"
            geometry={nodes.Plane_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane_3"
            geometry={nodes.Plane_3.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="chair"
          geometry={nodes.chair.geometry}
          material={textureMaterial}
          position={[0.482, 0.978, -1.616]}
          rotation={[-Math.PI / 2, 0, 3.141]}
          scale={0.914}
        />
        <group name="plant" position={[-4, 1.132, -3.752]}>
          <mesh
            name="mesh24448074"
            geometry={nodes.mesh24448074.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh24448074_1"
            geometry={nodes.mesh24448074_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh24448074_2"
            geometry={nodes.mesh24448074_2.geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="table"
          position={[0.962, 0, -4.319]}
          rotation={[0, -1.565, 0]}
        >
          <mesh
            name="Plane001_Plane002_BlackWood"
            geometry={nodes.Plane001_Plane002_BlackWood.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood_1"
            geometry={nodes.Plane001_Plane002_BlackWood_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood_2"
            geometry={nodes.Plane001_Plane002_BlackWood_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood_3"
            geometry={nodes.Plane001_Plane002_BlackWood_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood_4"
            geometry={nodes.Plane001_Plane002_BlackWood_4.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="imac"
          geometry={nodes.imac.geometry}
          material={textureMaterial}
          position={[0.492, 2.418, -4.745]}
          rotation={[Math.PI, -1.561, Math.PI]}
        />
        <mesh
          name="mouse"
          geometry={nodes.mouse.geometry}
          material={textureMaterial}
          position={[1.456, 2.418, -3.807]}
        />
        <group
          name="pikachu"
          position={[2.729, 3.03, -4.205]}
          rotation={[-Math.PI, 0.581, -Math.PI]}
        >
          <mesh
            name="mesh1465871970"
            geometry={nodes.mesh1465871970.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh1465871970_1"
            geometry={nodes.mesh1465871970_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh1465871970_2"
            geometry={nodes.mesh1465871970_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh1465871970_3"
            geometry={nodes.mesh1465871970_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh1465871970_4"
            geometry={nodes.mesh1465871970_4.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="keyboard"
          geometry={nodes.keyboard.geometry}
          material={textureMaterial}
          position={[0.236, 2.413, -3.888]}
        />
        <mesh
          name="screen"
          geometry={nodes.screen.geometry}
          material={textureMaterial}
          position={[0.492, 2.418, -4.745]}
          rotation={[Math.PI, -1.561, Math.PI]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/scene.glb");
